[versions]
# plgin
agp = "8.3.2"
kotlin = "1.9.25"
hilt = "2.44"
protobufPlugin = "0.9.4"

# androidx
material = "1.12.0"
coroutines = "1.8.1"
appcompat = "1.7.0"
coreKtx = "1.15.0"
activity = "1.9.3"
fragment = "1.8.5"
lifecycle = "2.8.7"
multidex = "2.0.1"
startup = "1.2.0"
webkit = "1.12.1"
recyclerview = "1.3.2"
constraintLayout = "2.2.0"
viewpager2 = "1.1.0"
swipeRefreshLayout = "1.1.0"
navigation = "2.8.3"
room = "2.6.1"
paging = "3.3.2"
anonotion = "1.9.1"

# compose
composeBom = "2024.10.01"
constraintLayoutCompose = "1.1.0"
accompanistCoil = "0.15.0"

# 第三方
protobuf = "3.18.0"
autoService = "1.0"
gson = "2.11.0"
glide = "4.16.0"
retrofit = "2.11.0"
okhttp3 = "3.11.0"
imageTools = "1.4.4"
agentWeb = "v5.0.6-androidx"

# test
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
leakcanary = "2.14"
blockCanary = "1.5.0" # compileSdk = 32 即android12 无法编译通过 (manifest <activity> has intent-filter exported = true )

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-starup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-navigation-dynamic-features-fragment = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# compose相关
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-material = { group = "androidx.compose.material", name = "material" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayoutCompose" }
accompanist-coil = { group = "com.google.accompanist", name = "accompanist-coil", version.ref = "accompanistCoil" }

# 第三方
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoService" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
image-tools-library = { group = "com.github.jv-lee.imagetools", name = "library", version.ref = "imageTools" }
agentweb-core = { group = "com.github.Justson.AgentWeb", name = "agentweb-core", version.ref = "agentWeb" }

# compiler
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-annotation-compiler = { group = "androidx.annotation", name = "annotation", version.ref = "anonotion" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
autoservice-compiler = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoService" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }


# test相关
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version = "1.7.3" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
blockcanary-android = { group = "com.github.markzhai", name = "blockcanary-android", version.ref = "blockCanary" }

[plugins]
buildVersion = { id = "build-version", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrainsKotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }

[bundles]
androidx = ["kotlinx-coroutines-core", "androidx-appcompat", "androidx-core-ktx", "material",
    "androidx-activity-ktx", "androidx-fragment-ktx",
    "androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel-ktx", "androidx-lifecycle-livedata-ktx",
    "androidx-multidex", "androidx-starup-runtime", "androidx-webkit",
    "androidx-recyclerview", "androidx-constraintlayout", "androidx-viewpager2", "androidx-swiperefreshlayout",
    "androidx-navigation-ui-ktx", "androidx-navigation-fragment-ktx",
    "androidx-room-ktx", "androidx-room-runtime"]
thirdPart = ["glide", "glide-okhttp3-integration", "glide-annotations",
    "retrofit", "retrofit-converter-gson", "retrofit-converter-scalars",
    "okhttp3-logging-interceptor", "gson", "protobuf-javalite", "auto-service"]
compiler = ["androidx-annotation-compiler", "androidx-room-compiler", "autoservice-compiler", "glide-compiler"]
test = ["junit"]
androidTest = ["androidx-junit", "androidx-espresso-core"]
debug = ["leakcanary-android"]
