/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_APK_AAR_SUPPORT is turned on or not
     */
    public static final boolean GN_APK_AAR_SUPPORT = true;
    /**
     * check if GN_APK_HAS_JNI_LIBRARIES is turned on or not
     */
    public static final boolean GN_APK_HAS_JNI_LIBRARIES = true;
}
